### ISSUE TITLE
AMD_Vanilla patch with stock kernel installed, Steam does not launch.

### ISSUE THREAD

**Issue by mikedebian** [AMD-OSX/AMD_Vanilla#1]
ASUS Prime X370-PRO
AMD 1800X

Have Mojave 10.14.3 installed, using the stock kernel with the AMD_Vanilla patch.

Boots fine, works fine, everything is good.

Steam does not launch. I suspect this is to 32-bit support on AMD CPUs?
Absolutely clean Mojave install.

Steam will launch with the prelinked patched amd kernel, using Mojave 10.14.1

Path:                  /Applications/Steam.app/Contents/MacOS/steam_osx
Identifier:            com.valvesoftware.steam
Version:               ???
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           steam_osx [2234]
User ID:               501

Date/Time:             2019-03-25 02:36:33.999 +0100
OS Version:            Mac OS X 10.14.3 (18D109)
Report Version:        12
Anonymous UUID:        2999F35E-0E1A-BF48-AB03-B86CE463FD8A

Time Awake Since Boot: 4800 seconds

System Integrity Protection: disabled

Crashed Thread:        Unknown

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [2234]

Backtrace not available

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0xffffffe4  ebx: 0x000a9000  ecx: 0xbff57b8c  edx: 0x0044c2a2
  edi: 0xbff57c34  esi: 0x0044be4e  ebp: 0xbff57b98  esp: 0xbff57b8c
   ss: 0x00000023  efl: 0x00010246  eip: 0x0044d4eb   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x00000000
  cr2: 0x0044d4e8
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     6

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 2923
    thread_create: 0
    thread_set_state: 0

**Comment by dhinakg** [comment]
This happens because the patches are still in beta and do not have OPEMU support. Steam is 32-bit, and 32-bit is not supported yet.

**Comment by XLNCs** [comment]
@mikedebian 
here is the 64 bit steam app .
[Steam-64.zip](https://github.com/AMD-OSX/AMD_Vanilla/files/3194004/Steam-64.zip)

**Comment by mikigal** [comment]
`~
❯ /Applications/Steam.app/Contents/MacOS/steam_osx
[2019-05-19 12:23:08] Startup - updater built Sep  8 2018 12:23:32
found breakpad via in process memory: '/Applications/Steam.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources'
Installing breakpad crash handler
[2019-05-19 12:23:08] Startup - updater built Apr 29 2019 14:00:35
found breakpad via in process memory: '/Users/mikigal/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Breakpad.framework/Versions/A/Resources'
Installing breakpad crash handler
SteamID:  0, universe Public
[2019-05-19 12:23:09] Verifying installation...
[2019-05-19 12:23:09] Verification complete
[2019-05-19 12:23:09] Shutdown`

@XLNCs You 64bit Steam crash for me
