### ISSUE TITLE
Catalina installer stuck on "administrator is creating non-ejectable disk image"

### ISSUE THREAD

**Issue by pexcn** [AMD-OSX/AMD_Vanilla#100]
Hi guys:
A few days ago, I follow [this guide](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/amd-config.plist/amd-config) try install macOS Catalina (10.15.3) on AMD FX series platform using OpenCore (v0.5.6). Unfortunately stuck on those lines more than 30 minutes:
```bash
# last two lines
imageboot_setup_new: successfully authenticated /Install macOS Catalina.app/Contents/SharedSupport/BaseSystem.img
IOHDIXController: NOTE: administrator is creating non-ejectable disk image
```
30 minutes later, when I disconnect the USB installer drive, screen will append this log (Looks like the USB doesn't seem to be read?):
```bash
USB device 05E3073612300000 - Generic, USB Storage - detected termination of interfaceNub, currentPowerState 1, provider is non-NULL
003517.887903 AppleUSBOHCIPort@12400000: AppleUSBHostPort::disconnect: persistent enumeration failures
```

#### My desktop specifications
| Hardware | Model |
| --- | --- |
| CPU | AMD FX 6300 |
| Motherboard | ASUS M5A97 LE R2.0 |
| Graphic | NVIDIA GTX 650 (1GB, Kepler, GK107) |
| RAM | Kingston 4 GB DDR3 1600MHz × 2 |
| SSD | SanDisk 128 GB |
| Sound | Realtek ALC887 |
| Network | Realtek RTL8168/8111/8112 |

#### My BIOS settings
- Disabled: CSM
- Enabled: EHCI/XHCI Hand-off

#### My EFI configs
https://github.com/pexcn/hackintosh-amd-fx-series/tree/master

#### Note
I was post the [same topic](https://amd-osx.com/forum/viewtopic.php?f=61&t=10272&sid=4194ebd3027b7430ce587ea8bf80f4b4) on the amd-osx forum, but no reply, so I had to post an same topic on github for get help.
Finally, my English is not good, I am Taiwanese. I hope you can understand what I mean. 🙂

**Comment by pexcn** [comment]
Append the screenshot:
![iX50OMU](https://user-images.githubusercontent.com/4590439/76696647-c6061080-66c8-11ea-8ad3-50644b530141.jpg)

**Comment by itdawn** [comment]
This version does not support NVIDIA graphics

**Comment by pexcn** [comment]
> This version does not support NVIDIA graphics

Hi @itdawn, thanks for your reply.
My graphic card is GTX 650 (GPU: GK107 core), that's kepler series, according to: https://khronokernel-3.gitbook.io/gpu-buyers-guide/modern-gpus/nvidia-gpu#native-nvidia-gpus
> Kepler Series (GTX 6xx, 7xx) Highest Supported OS: Current/Catalina

**Comment by itdawn** [comment]
> Hi @itdawn, thanks for your reply.
> 
> > This version does not support NVIDIA graphics
> 
> My graphic card is GTX 650 (GPU: GK107 core), that's kepler series, according to: https://khronokernel-3.gitbook.io/gpu-buyers-guide/modern-gpus/nvidia-gpu#native-nvidia-gpus
> 
> > Kepler Series (GTX 6xx, 7xx) Highest Supported OS: Current/Catalina

That only be supported under 10.13，and you can reference [XJN‘s Blog](https://blog.xjn819.com/)

**Comment by pexcn** [comment]
I was follow [this guide](https://khronokernel.github.io/Getting-Started-With-ACPI/Desktops/desktop-ec.html), ACPI patch was perfected.

GK107 core GPUs natively supported by Catalina, no driver needed: https://www.tonymacx86.com/threads/will-my-nvidia-graphics-card-work-with-macos-list-of-desktop-cards-with-native-support.283700/

**Comment by Pasarel** [comment]
Hello, I have the same problem. AMD FX8350, Gigabyte GA-990FXA-UD3, Radeon RX 460. If I make sure there is NO APFS partition on any of the devices I have connected to the motherboard (whether I'm booting from them or not), I can successfully boot into the installer. 

That means I have to install Catalina to HFS+ - which can't happen, the installer gets stuck, with error logging reporting "Unable to get fs for (null)". 

Of course, I can partiton my drive to APFS _inside_ the installer, and I did manage to complete the first part of the Catalina installation this way (but it took around 6 hours). However after the computer rebooted so as to complete the installation from local storage, I again was not able to boot, with the same message: "administrator is creating non-ejectable disk image".

Some help would be appreciated, thank you.

**Comment by dhinakg** [comment]
Issue tracker is for patch issues, not for support, go to the discord.

**Comment by pexcn** [comment]
@Pasarel I still haven't solved this problem, that's too troublesome, I gave up temporarily.

> Issue tracker is for patch issues, not for support, go to the discord.

Oh, sorry, I do not know there was discord before.

**Comment by marcinkk** [comment]
did you manage to fix this error: administrator is creating non-ejectable disk image??
