### ISSUE TITLE
Support 10.15.4?

### ISSUE THREAD

**Issue by riverscn** [AMD-OSX/AMD_Vanilla#106]
2700x
10.15.3 -> 10.15.4
17h

install system update failed.

**Comment by cyjyyd** [comment]
amd ryzen9 3900x
gigabyte x570 arous pro wifi
17th

install system update failed

**Comment by sherylynn** [comment]
1700 ryen
10.15.3 -> 10.15.4
install system update failed.

**Comment by cyjyyd** [comment]
Hey guys! try the bate6 update patches.I am now updated to 10.15.4 everthing seems to be fine except the audio

**Comment by radianttap** [comment]
It's already supported, one patch is new, from a week ago.
Update your patch list and you're good to go.

**Comment by riverscn** [comment]
Thank you guys!
I updated patch and it works!
