### ISSUE TITLE
Adobe Photoshop 2020 crashes.

### ISSUE THREAD

**Issue by cyjyyd** [AMD-OSX/AMD_Vanilla#107]
CPU:Ryzen9 3900x
macOS version:10.15.3
15h/16h or 17h:17th
I am using and can reproduce on the latest patches:
It crashes when I chose select-color range
crash report:
[Process.txt.zip](https://github.com/AMD-OSX/AMD_Vanilla/files/4378871/Process.txt.zip)

**Comment by mikigal** [comment]
`sudo rm -r /Applications/Adobe\ Photoshop\ 2020/Adobe\ Photoshop\ 2020.app/Contents/PlugIns/Required/Extensions/MMXCore.plugin

sudo rm -r /Applications/Adobe\ Photoshop\ 2020/Adobe\ Photoshop\ 2020.app/Contents/PlugIns/Required/Extensions/FastCore.plugin

sudo rm -r /Applications/Adobe\ Photoshop\ 2020/Adobe\ Photoshop\ 2020.app/Contents/Required/Deep_Font

sudo rm -r /Library/Application\ Support/Adobe/Plug-Ins/CC/File\ Formats/Camera\ Raw.plugin`

Removing these plugins fixed Photoshop issues for me.

**Comment by cyjyyd** [comment]
I've tried following orders.Problem still exists.When I hit the menu bar and choose select-color range or select-main body.It just crashed.I looked at the crash report and this time I don't think the issue is caused by these plugins.

**Comment by cyjyyd** [comment]
help! anyone?

**Comment by sstruct** [comment]
https://gist.github.com/XLNCs/86d7a391e46f85a04d28db171656b458

reinstall PS then have a try :)
