### ISSUE TITLE
IS L463_CPUFAMILY correct?

### ISSUE THREAD

**Issue by MK107k** [AMD-OSX/AMD_Vanilla#108]
https://github.com/AMD-OSX/AMD_Vanilla/blob/a464c72fd68e79c624f3f6eb45775e229bc28e0d/17h/patches.plist#L463

**Comment by 404errors** [comment]
Are you facing trouble when  upgrading to 10.15.4? I got the same issue containing error CPUFAMILY_INTEL_PENRYN

**Comment by MK107k** [comment]
Yes, I got it when doing a new install.

**Comment by 404errors** [comment]
I've just tried merging changes in his latest commit into my OC config.plist and it works. Updated to 10.15.4
