### ISSUE TITLE
Not booting in R5 2600X, fine in R7 3800X

### ISSUE THREAD

**Issue by EnekoT2001** [AMD-OSX/AMD_Vanilla#109]
**CPU: Ryzen 5 2600x**
**macOS version: 10.15.3**
**15h/16h or 17h: 17h**
**I am using and can reproduce on the latest patches:**

**Describe the bug**
When booting on my friend's r5 2600x based system the screen goes black, and if remove npci=0x2000 from the boot-arg it freezes at random. It works fine in my 3800X with the same chipset. 
We made a .plist from scratch for her system and checked all twice and is fine. Also tried a copy of mine with minor tweaks, no change
I have an Nvidia GPU and hers is an amd r9 so maybe is that, but isn't amd supposed to be more compatible?
We also tried using different smbios and nothing

**Screenshots**

**Comment by dhinakg** [comment]
*When* does the screen go black?
This is almost certainly a setup issue, so go to the Discord or to the forums.

**Comment by EnekoT2001** [comment]
> _When_ does the screen go black?
> This is almost certainly a setup issue, so go to the Discord or to the forums.

Is after it starts booting, a lot of text appears and the screen goes black, i think about when it finishes the early boot but i'm not sure, if i disable the npci option it just freezes at random, the motherboard doesn't have an above 4g option

**Comment by dhinakg** [comment]
This is a configuration issue and there is no issue with the patches. Go to the discord or the forums.
