### ISSUE TITLE
Can’t setup 

### ISSUE THREAD

**Issue by MrBenFTW** [AMD-OSX/AMD_Vanilla#11]
Hi, when I go to setup my newly installed Mojave, when I get to the privacy screen it panics or reboots when I press continue.

**Comment by XLNCs** [comment]
Hi !
https://www.insanelymac.com/forum/topic/335877-amd-mojave-kernel-development-and-testing/?do=findComment&comment=2658085

i have posted a way to bypass this issue , have a look .

**Comment by MrBenFTW** [comment]
I followed your article but after rebooting I just have a black screen and white text coming up every 3 seconds saying something along the lines of ‘vm_map_delete’

**Comment by XLNCs** [comment]
whats your system specs ?

**Comment by MrBenFTW** [comment]
Athlon X4 860K I think. 
MSI (Can’t remember model) 
HDD
8GB ram

**Comment by MrBenFTW** [comment]
Resorted to just using macos high Sierra. Unfortuanatly cannot use the latest xcode now or swift  5
