### ISSUE TITLE
Support for ryzen 9 3900 (non x, non pro) 

### ISSUE THREAD

**Issue by PeLLmEn** [AMD-OSX/AMD_Vanilla#115]
CPU: Ryzen 9 3900
macOS version: 10.15.4
17h

There is no support for ryzen 9 3900, but I've installed and booted to macos catalina normaly. Macos can't identify processor...

I can provide all you need for this processor. Just tell what I have to do.

**Comment by radianttap** [comment]
You did install and it runs, right? So there's your support. :)

Displayed name inside macOS is irrelevant, just ignore it.

**Comment by jdkid86** [comment]
Hello, I also have a 3900 without X and I confirm that it works correctly. Power management verified and with temperatures lower than windows.

I would like to make a query related to the "Ryzentosh" platform. In this type of installation, are there problems with the activation of some software licenses? In my case I cannot activate Wave 11 with Logic X.
