### ISSUE TITLE
BIOS SETUP plz award 

### ISSUE THREAD

**Issue by Cekcu-Yto4ka** [AMD-OSX/AMD_Vanilla#116]
CPU: fx 4300
macOS catalina 10.15
15h/16h 
ga-78lmt-s2p v5 
I wanted to install mac oc catalina, created a flash drive with opencore, I can’t configure the BIOS, mac os installation does not start, help (sorry for bad English, translator)))

**Comment by Cekcu-Yto4ka** [comment]
![WqaD27HTkv4](https://user-images.githubusercontent.com/64467408/80480175-9dc92d00-8969-11ea-80c6-cd121593d0a4.jpg)
![Z0OKoaonZkQ](https://user-images.githubusercontent.com/64467408/80480179-9efa5a00-8969-11ea-9687-c9c3923c46e6.jpg)
![vEplJEn2rsY](https://user-images.githubusercontent.com/64467408/80480181-9f92f080-8969-11ea-8f55-4f8b295a87bc.jpg)
![B_ioa66HnBQ](https://user-images.githubusercontent.com/64467408/80480182-a0c41d80-8969-11ea-8052-f934a66db1ad.jpg)
![6Td4EJl1p18](https://user-images.githubusercontent.com/64467408/80480183-a15cb400-8969-11ea-9de4-a646e5a3e588.jpg)

**Comment by HoshiYamazaki** [comment]
Verbose log?
