### ISSUE TITLE
 how to make opencore bootable flash drive on windows 10 legas bios

### ISSUE THREAD

**Issue by Cekcu-Yto4ka** [AMD-OSX/AMD_Vanilla#118]
fx 4300
ga-78lmt-s2p (legacy bios)
catalina 10.15.3
**15h/16h 
opencore 0.5.7. 
How to make opencore bootable flash drive on windows 10 legas bios

**Comment by rrroyal** [comment]
https://dortania.github.io/OpenCore-Desktop-Guide/installer-guide/
