### ISSUE TITLE
usb printer

### ISSUE THREAD

**Issue by anyen888** [AMD-OSX/AMD_Vanilla#12]
i have hp printer 1025
everything works..only usb printer make system crash..it detect the printer...isntall correctly,,,
the issue is when i press print..
the keyboard and mouse not function and crash...and system hang
i am on mojave 10.14.5 by the way...the issue persist on previous build

**Comment by anyen888** [comment]
anyone?

**Comment by midi1996** [comment]
This issue has nothing to do with the git.
