### ISSUE TITLE
NVIDIA web drivers not loading in macOS High Sierra

### ISSUE THREAD

**Issue by thatdhruv** [AMD-OSX/AMD_Vanilla#13]
Hi! I have done a vanilla install of macOS High Sierra and have also installed the NVIDIA web drivers with it.
But the problem is that macOS uses the default graphics driver on each reboot; so is there a way to configure the operating system to use the NVIDIA web drivers each time I reboot or use my computer?
I'm really annoyed by doing the same routine every time of restarting my computer, going to NVIDIA preferences, entering my password, and then restarting again to get the graphics.

Thanks in advance.

**Comment by XLNCs** [comment]
Hi !
Install latest version of lilu and whatevergreen kext in clover kexts folder 
tick Nvidia Web option in clover config.plist
then reboot

**Comment by thatdhruv** [comment]
Thanks! 😊

**Comment by thatdhruv** [comment]
Thanks! 😊
