### ISSUE TITLE
AMD Athlon(tm) 64 X2 Dual Core Processor

### ISSUE THREAD

**Issue by AthlonAMDx64** [AMD-OSX/AMD_Vanilla#137]
Hallo! Tell me please, how to create and use Catalina's kernel patch for this processor:
 === [ GetCPUProperties ] ========================
0:000  CPU Vendor = 68747541 Model=40F32
0:000   The CPU not supported SSE4.1
0:000  BrandString = AMD Athlon(tm) 64 X2 Dual Core Processor 5200+

Thank you wery much!

**Comment by TurannUl** [comment]
U need SSE4.2 Ability To Run Sierra and Higher Versions,Close your issue

**Comment by AthlonAMDx64** [comment]
But Sierra and Higher Versions run on 
http://www.cpu-world.com/CPUs/Core_2/Intel-Core%202%20Duo%20Mobile%20P8400%20AV80577SH0513M.html without SSE4.2 (many thanks and big respect to dosdude1)

**Comment by TurannUl** [comment]
Ask your question AMD-OSX Forum or AMD-OSX Facebook

**Comment by menditsa** [comment]
> Ask your question AMD-OSX Forum or AMD-OSX Facebook

Try using the discord server
