### ISSUE TITLE
Update For BS Beta 7 

### ISSUE THREAD

**Issue by TurannUl** [AMD-OSX/AMD_Vanilla#141]
**CPU:**Ryzen 5 3500x
**macOS version:**11.0 Beta 6
**15h/16h or 17h:**17h
**I am using and can reproduce on the latest patches:**yes 

**Describe the bug**
A clear and concise description of what the bug is.no bug It stable except Handoff not workin (Fenvi T919)

**Screenshots**

**Comment by menditsa** [comment]
No need to have opened this issue as per the chat on the discord server. Please close.
