### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by thatdhruv** [AMD-OSX/AMD_Vanilla#16]
Hi! I've set my hackintosh up along with the NVIDIA web drivers and the CUDA driver as well. But I still have one problem, I don't get GPU or hardware acceleration in any programs. I'm using High Sierra so graphics compatibility is not an issue.
For example, whenever I use quicktime to play any HD videos, they play just fine. But when I use VLC, the videos start lagging and audio doesn't output properly. I've messed with various preferences as well as video codecs, but can't figure it out.

In the end, I would like to find a solution for my videos lagging and stuttering in VLC; is it a GPU issue or am I missing some settings?

Thanks in advance,
thatdhruv@gmail.com

EDIT: I have a 4GB graphics card, and macOS only shows 256MB (and I presume that is the problem itself)
I have a GTX 1050 Ti

**Comment by dhinakg** [comment]
Not related to the patches.
