### ISSUE TITLE
Crash On Boot

### ISSUE THREAD

**Issue by motoxnate** [AMD-OSX/AMD_Vanilla#18]
Hi, hopefully this is a simple issue. I hope that I just missed something during setup. 

I have a clean installation of High Sierra 10.13.6 on a blank drive. I installed Clover r4934 and imported my working config from 10.12 and kexts. Then I coped the patches into the kernel patches and verified they are correct in Clover Configurator. 

When I boot 10.13 from Clover I get verbose text that appears to be working, then the line of:
++++++++++++++++++++++++++++++++++++++++++++++++++++++
Then my PC restarts. 

Specs: 
ASUS X370-Pro Motherboard
Ryzen 7 1700x @3.4GHz, no OC
16GB Corsair Vengeance 3200 (not running full speed for stability)
Sapphire R9 280x Toxic

**Comment by anyen888** [comment]
just replace the config.plist at clover boot depend on your  cpu

**Comment by motoxnate** [comment]
![IMG_3142](https://user-images.githubusercontent.com/12929241/59118514-60594c80-891e-11e9-894b-32db2ba6d3de.jpg)

With the unmodified clover config imported from 17h folder. Maybe you have seen this before?

**Comment by anyen888** [comment]
I think the problem..is you are not using mojave...10.14.5
The config.plist is for latest mojave

**Comment by anyen888** [comment]
And you use prelink kernel before...just dont use this...instead use prelink kernel depends of osx version you are using

**Comment by anyen888** [comment]
If you use mojave than give this clover and kext a try
And you have to change the config.plist
https://www.dropbox.com/s/7ak4if15vgibnup/CLOVER.zip?dl=0

**Comment by motoxnate** [comment]
I was hoping to install High Sierra, but Mojave should be pretty stable by now I suppose. 
I will try that. You say I still need the prelinked Kernel though?

**Comment by Shaneee92** [comment]
Depends which version of 10.13.6 you are booting. See the readme to see which versions are supported. You don't need to touch/modify and kernels/prelinkedkernels.

**Comment by dhinakg** [comment]
Closing as this seems to be fixed, if not just comment and I'll reopen.
