### ISSUE TITLE
XAMPP-VM/Hypervisor Framework not supported

### ISSUE THREAD

**Issue by mikigal** [AMD-OSX/AMD_Vanilla#2]
XAMPP-VM report that CPU is unsupported. It looks that it is issue with not working Hypervisor framework. Virtualization works (tested with VMWare Fusion).

Ryzen 7 1700
ASUS B350 Plus
macOS 10.13.6 (17G5019)

![igy354qy6i](https://user-images.githubusercontent.com/10632503/54967023-6a51ed00-4f76-11e9-8328-0ffc27123c34.png)

**Comment by Shaneee92** [comment]
Because it's not an Intel CPU it doesn't have VTX or the Hypervisor it is looking for.
