### ISSUE TITLE
TP-Link Archer T2UH not working in macOS Mojave

### ISSUE THREAD

**Issue by DedoGamingONE** [AMD-OSX/AMD_Vanilla#20]
Hi! I installed the drivers from TP-Link's official website, and for some reason, I am unable to use or even open the WirelessUtility app. I wonder if the drivers or maybe the application might be 32-bit. 
Hoping for any help. Thanks!

**Comment by dhinakg** [comment]
A crash when opening would mean that the app is 32-bit.

**Comment by DedoGamingONE** [comment]
isnt this app built for mojave?

**Comment by DedoGamingONE** [comment]
here is the downloads page
https://www.tp-link.com/us/support/download/archer-t2uh/

**Comment by tuancuong92** [comment]
Vanilla AMD macOS doesnt support 32bit mode. You read at readme of this project :(

**Comment by DedoGamingONE** [comment]
Is there a way to run 32bit only apps?

**Comment by tuancuong92** [comment]
Only one solution is intall the legacy amd osx, but the latest version is 10.14.1, icloud and facetime are not work, and the performance is drop a bit

**Comment by DedoGamingONE** [comment]
Is there another way? Because I got it working before

**Comment by dhinakg** [comment]
There is no way to run 32-bit apps with the vanilla patches.

**Comment by DedoGamingONE** [comment]
Ok I found a fix to the problem, but doesn’t that mean I can’t run half of the apps made for macOS
