### ISSUE TITLE
Mojave 10.14.5 rx570 8GB opencl memory clock set to 300mhz

### ISSUE THREAD

**Issue by shashika05** [AMD-OSX/AMD_Vanilla#21]
Benchmark results and adobe rendering results gets low, Cause of maxium frequency is set to 300mHz.

**Comment by FlexIDK** [comment]
confirm on rx580 8gb. Geekbench only 40k score. Chrome need disable hardware rendring.

**Comment by bedlamss** [comment]
I have tested more than 10 video cards rx 470-580. clock state 300 mhz, but metal api has good performance

**Comment by DouBaLee** [comment]
I use 2600x,Giga b450 WiFi Pro,vega 56
the GPU frequency is set to 800mhz
How to fix it?

**Comment by dhinakg** [comment]
This is a known cosmetic issue not specific to AMD processors. The actual clock speed is fine.
