### ISSUE TITLE
Hardware list

### ISSUE THREAD

**Issue by beefon** [AMD-OSX/AMD_Vanilla#23]
Could somebody perhaps share their hardware lists so I could have a reference system that I can expect to work with these patches? Or is there a forum where the active discussions are happening?

Also, have you tried 10.15 betas?

**Comment by dhinakg** [comment]
The supported CPUs are listed in the README. You can find more support at the AMD OS X discord at https://discord.gg/kEH5U4. 
10.15 is probably not going to be worked on until general release, because of the build by build nature of the patches.

**Comment by beefon** [comment]
> The supported CPUs are listed in the README

By hardware I meant motherboards. I understood that AMD CPUs are supported since this whole repo is all about supporting AMD CPUs.

> You can find more support at the AMD OS X discord at https://discord.gg/kEH5U4

Why would one go to discord to discuss hardware lists? Also, the link is broken.

**Comment by dhinakg** [comment]
The patches are CPU-specific, not motherboard-specific, or it would be
listed in the README. Therefore any motherboard should work.

The discord is the forum where discussions have been occuring. You can also
go to the website.
Here is an updated link: https://discord.gg/QhWcz8U
