### ISSUE TITLE
can anyone explain what i need ?

### ISSUE THREAD

**Issue by vesaldivan** [AMD-OSX/AMD_Vanilla#25]
hi i have an AMD 6300 .
how i can to inistall the mac os on my pc ?
i know that i must to using H15 method.
what i need to download? 
im a beginner please explain step by step
thank you my friends .

**Comment by dhinakg** [comment]
See [the AMD OS X KB](https://kb.amd-osx.com). This place is not for support.
For support, go to the [AMD discord](https://discord.gg/nx9sNhv).
