### ISSUE TITLE
AMD Ryzen Zen2 Support

### ISSUE THREAD

**Issue by sekkit** [AMD-OSX/AMD_Vanilla#26]
Can Zen2 be compatible with Darwin kernel?

**Comment by wangwindlong** [comment]
also looking for the answer, and hesitate to buy 3700x cpu

**Comment by dhinakg** [comment]
![image](http://pomf.azurewebsites.net/Discord_2019-07-22_11-11-46.png)

**Comment by fancyIX** [comment]
So where is the fix? I didn't see any updates of this repo recently.
