### ISSUE TITLE
GPU performance

### ISSUE THREAD

**Issue by FlexIDK** [AMD-OSX/AMD_Vanilla#27]
If use patch 15h_16h on Ryzen 2600(X) - GPU have full performance
After use 17h - - GPU have only 30% performance

Sample:
15h_16h - https://browser.geekbench.com/v4/compute/4337294

17h - https://browser.geekbench.com/v4/compute/4337069

**Comment by hollowpixel** [comment]
@FlexIDK Could you share your working 15h_16h EFI folder please? I'm having a similar issue with my 3700x except both give me 30% performance.

Thanks

**Comment by FlexIDK** [comment]
> @FlexIDK Could you share your working 15h_16h EFI folder please? I'm having a similar issue with my 3700x except both give me 30% performance.

I'm manual replace <key>KernelToPatch</key> section to this:
- https://raw.githubusercontent.com/AMD-OSX/AMD_Vanilla/master/15h_16h/patches.plist

**Comment by tctien342** [comment]
> > @FlexIDK Could you share your working 15h_16h EFI folder please? I'm having a similar issue with my 3700x except both give me 30% performance.
> 
> I'm manual replace KernelToPatch section to this:
> 
> * https://raw.githubusercontent.com/AMD-OSX/AMD_Vanilla/master/15h_16h/patches.plist

Did you facing with issues like audio is faster than picture while watching YouTube, just don't touch your mouse or keyboard and watching that happen, maybe tscsync ?

**Comment by hollowpixel** [comment]
@FlexIDK I have those patches and still only get 30% performance, I'm thinking there's something in your config or EFI folder that makes the x580 fully work with the 15h_16h patches.

Could you please share your EFI folder or config.

Thanks,

**Comment by dhinakg** [comment]
A fix is currently in testing

**Comment by stefanivic** [comment]
@dhinakg is there any way to test or help with this. I am running Ryzen 6 2600 with RX 570 and I am noticing a poor G:PU performance, even with OS animations.

**Comment by KITSTABAdrienBaron** [comment]
Experiencing same issues with a Ryzen 1700X and AMD RX570. Issues are mostly (some) lag in some UI animation, most noticable thing is Google Maps is really slow to load tiles.
If you need me to run diagnostics or need more details about my config feel free to ask (I'm a software developer)

**Comment by dhinakg** [comment]
Patches have been updated.

**Comment by DouBaLee** [comment]
My VEGA 56,run Geekbench4 in Windows,score is about 19K.
in MacOS,score is about 12K

**Comment by KITSTABAdrienBaron** [comment]
@DouBaLee have you tried the latest patch? It really improved things a lot on my config (RX 570/Ryzen 1700X)

**Comment by DouBaLee** [comment]
> @DouBaLee have you tried the latest patch? It really improved things a lot on my config (RX 570/Ryzen 1700X)

YES，i use the latest 17h patch.before that,my VEGA 56 geekbench4 score was 40K.OMG,i was wrong.my VEGA 56 run Geekbench in Win10 is 190K,in MacOS is 120K.
