### ISSUE TITLE
Interface stuttering GTX 650 + FX6300

### ISSUE THREAD

**Issue by twikoffin** [AMD-OSX/AMD_Vanilla#28]
Motherboard : Gigabyte GA-970A-DS3P
CPU: AMD FX6300
GPU: Nvidia GTX 650 1GB

My GPU is working out of box with transparent dock and menu bar, dual monitor (VGA+DVI with sound) working too.
But I noticed that the interface is not smooth, it is stutters and lags sometimes.

Is this a binary patch issue or just nvidia + amd trouble?
Thanks

**Comment by surajmandalcell** [comment]
Whats your refresh rate?

**Comment by twikoffin** [comment]
60hz

**Comment by surajmandalcell** [comment]
You probably don't have hardware acceleration working. Check if your hardware acceleration is enabled or not.

**Comment by twikoffin** [comment]
@surajmandalcell
Please do not reply in this issue

**Comment by dhinakg** [comment]
It is NVIDIA GPU + AMD CPU issues.
