### ISSUE TITLE
It must need SEE4.1 for AMD？

### ISSUE THREAD

**Issue by InoriHimea** [AMD-OSX/AMD_Vanilla#31]
I have acer notebook with APU A6-3420M。I already try to use this method to make a USB installer disk。but it run to “End Random....” with a line “+++++”，and never run forever。
    by the look up CPUID in Windows, I find it not have SEE4.1，but SEE1-4a。So I can't know what the problem it is。
   I try to install 10.14 and 10.13 for this method。Another，it also try to install 10.12 and 10.11 with XNU kernel booted by Enoch，and then run to LengcyUSB.... ，it reboot forever。It means that this method need run in harddisk and not in USB？

**Comment by dhinakg** [comment]
Yes, SSE4.1 is required.
