### ISSUE TITLE
[Question] Can we update to 10.14.6 Supplemental Update without extra patch entries?

### ISSUE THREAD

**Issue by tedli** [AMD-OSX/AMD_Vanilla#32]
macOS had 10.14.6 Supplemental Update released. Is the latest patches work with this version?

![image](https://user-images.githubusercontent.com/3324663/62589860-2e07a380-b8fd-11e9-929d-d41b65623cba.png)

**Comment by dhinakg** [comment]
![image](https://user-images.githubusercontent.com/17605561/62595858-db929c80-b894-11e9-8225-08bd433274a4.png)
