### ISSUE TITLE
Illegal instruction: 4 in just about every Steam game

### ISSUE THREAD

**Issue by rafnogueira** [AMD-OSX/AMD_Vanilla#33]
My CPU is a Ryzen 3700X, and i follow the patches with success and installed Mac OS, every software works just fine, but talking about games, in Steam my entire library of games is not opening always get this crash error report
Running from command line:

> Mac-Pro:Half-Life 2 rafael$ ./hl2_osx 
> Illegal instruction: 4
> 

Crash Report in another games like Shogun 2 Total War: 

> Process:               Total War SHOGUN 2 [644]
> Path:                  /Volumes/VOLUME/*/Total War SHOGUN 2.app/Contents/MacOS/Total War SHOGUN 2
> Identifier:            com.feralinteractive.shogun2tw
> Version:               ???
> Code Type:             X86 (Native)
> Parent Process:        ??? [1]
> Responsible:           Total War SHOGUN 2 [644]
> User ID:               501
> 
> Date/Time:             2019-08-07 09:49:12.740 -0300
> OS Version:            Mac OS X 10.14.6 (18G84)
> Report Version:        12
> Anonymous UUID:        DD0681C8-4F35-18A5-D589-2E3114AA992D
> 
> 
> Time Awake Since Boot: 180 seconds
> 
> System Integrity Protection: disabled
> 
> Crashed Thread:        Unknown
> 
> Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
> Exception Codes:       0x0000000000000001, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Signal:    Illegal instruction: 4
> Termination Reason:    Namespace SIGNAL, Code 0x4
> Terminating Process:   exc handler [644]
> 
> Backtrace not available
> 
> Unknown thread crashed with X86 Thread State (32-bit):
>   eax: 0xffffffe4  ebx: 0x0006f000  ecx: 0xbff90f7c  edx: 0x051021ee
>   edi: 0xbff91024  esi: 0x05101d99  ebp: 0xbff90f88  esp: 0xbff90f7c
>    ss: 0x00000023  efl: 0x00010246  eip: 0x0510343b   cs: 0x0000001b
>    ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x00000000
>   cr2: 0x05103438
>   
> Logical CPU:     8
> Error Code:      0x00000000
> Trap Number:     6
> 
> 
> Binary images description not available
> 
> 
> External Modification Summary:
>   Calls made by other processes targeting this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by all processes on this machine:
>     task_for_pid: 94
>     thread_create: 0
>     thread_set_state: 0
> 
> Model: MacPro5,1, BootROM 220.240.2.0.0, 8 processors, 3,59 GHz, 16 GB, SMC 1.39f11
> Graphics: Radeon RX 480, Radeon RX 480, spdisplays_pcie_device, 8 GB
> Memory Module: DIMM1, 8 GB, DDR4, 2400 MHz, Unknown, Unknown
> Memory Module: DIMM2, 8 GB, DDR4, 2400 MHz, Unknown, Unknown
> Network Service: Ethernet, Ethernet, en0
> Serial ATA Device: ST9500325AS, 500,11 GB
> Serial ATA Device: ST2000DM006-2DM164, 2 TB
> Serial ATA Device: ST1000DM010-2EP102, 1 TB
> Serial ATA Device: SanDisk SDSSDA240G, 240,06 GB
> USB Device: USB 3.1 Bus
> USB Device: USB 3.1 Bus
> USB Device: USB Audio Device
> USB Device: AMD SR4 lamplight Control
> USB Device: Gaming Mouse G402
> USB Device: Usb Gaming Keyboard
> USB Device: MI 8
> Thunderbolt Bus: 

Does anyone knows why this is happening ? The only games from my library that i tested that works is hearts of iron 4

**Comment by Ashkinaldloshi** [comment]
OS X on AMD Native only support 64bit apps. Some games are not 64 bit so it won't run. After Catalina update later this year, you will get the same on normal mac becouse they are cutting support for 32bit apps in macos so Steam must update they library for catalina to only 64bit apps

**Comment by XLNCs** [comment]
32 bit support is not there so 32 bit apps will crash !
