### ISSUE TITLE
Slow multicore performance

### ISSUE THREAD

**Issue by FlexIDK** [AMD-OSX/AMD_Vanilla#34]
After new patch 17h i have slow multicore performance -50%

CPU: https://browser.geekbench.com/v4/cpu/14276042 - Single core - OK. Multicore -50%
GPU: https://browser.geekbench.com/v4/compute/4428270 - GPU perfect performance

**Comment by FlexIDK** [comment]
Cinebench score: only 1085 
Before patch: 3036

**Comment by FlexIDK** [comment]
hmmm... I'm try rollback patch to previous version (change version kext / change version clover), and multicore performance same...
I'm think, this bug only in 10.14.6 version. Before, on version 10.14.5 i'm have full performance. Cinebench score:
- 10.14.5: 3036. 
- 10.14.6: 986-1084 
(((

**Comment by FlexIDK** [comment]
Find error in bios. 
Sorry

**Comment by beefon** [comment]
@FlexIDK what was the issue with your bios settings?

**Comment by FlexIDK** [comment]
@beefon i'm overclock my CPU and memory. After this, my cpu have -50% performance)))
