### ISSUE TITLE
Can Vanilla support AMD-V (SVM)?

### ISSUE THREAD

**Issue by tylinux** [AMD-OSX/AMD_Vanilla#36]
I installed macOS 10.14.4 on my Ryzen 1700 device via Valilla. Everything is perfect except Virtual Machine.VirtualBox is usable but bad performance。 I confirm that SVM support is turned on in the BIOS setup，but the output of `sysctl machdep.cpu.features` command don't contain 'svm'. Is there any way to support it ?

**Comment by tedli** [comment]
@tylinux 
Hi. Have look at this https://github.com/moby/hyperkit/issues/230

I don't think it's vanilla's fault nor virtual box. Because apple never have an AMD based machine, so software vendors assume that they don't need to compatible with AMD. Also software vendors can't fully test their softwares on AMD hackintosh since the machine specs varies.

I'm using VMs on AMD hackintosh, the vmware fusion works. However only ver 10 works (10.1.6 (12989998)), the latest 11 doesn't.

**Comment by zalivar71** [comment]
Hi,
I run and working with Virtualbox on my AMD Ryzen
And Virtual PC has good speed and see real processor. 

CPU Perfomance is the same when I ran Virtualbox with Windows on Ubuntu in this PC (I use it for MetaTester)
![изображение](https://user-images.githubusercontent.com/54080051/63077725-f4a8e680-bf41-11e9-98e9-26f5ff4285f8.png)

**Comment by tedli** [comment]
@zalivar71 
Hi,
Could you please provide which version of VirtualBox you are using. I'm also interested in VirtualBox, since the vmware only provide paid license.

**Comment by zalivar71** [comment]
@tedli 
Version 6.0.10 r132072 (Qt5.6.3)
And my config of VirtualPC
![image](https://user-images.githubusercontent.com/54080051/63078293-b9a7b280-bf43-11e9-8190-081f244d5776.png)
![image](https://user-images.githubusercontent.com/54080051/63078306-be6c6680-bf43-11e9-806f-50ffc464f58e.png)
![image](https://user-images.githubusercontent.com/54080051/63078311-c2988400-bf43-11e9-9e7e-1651a8d153d2.png)

PS I sure you checked, but I should to ask:), did you checked Virtualisation Checkbox in BIOS in CPU Options? Some Hackintosh manuals recommended disable this function.

**Comment by tedli** [comment]
@zalivar71 
Thanks for reply. I did check the Virtualization (SVM) in BIOS (SVM enabled). Indeed many manuals told to turn it off. I don't know why. But for my machine, turning SVM on didn't trick me, everything works fine.

**Comment by zalivar71** [comment]
Except Virtualisation )
My motherboard ASRock A320M-HDV. I don't know where to look any difference more (

**Comment by tylinux** [comment]
I know it's not vanilla's fault nor virtual box. I just want to know if there is a way to patch kernel or something else to let application like `VirtualBox` or `sysctl machdep.cpu.features` to know this machine support svm, maybe my vm's performance will be better.

I use `libcupuid` to detect my cpu info, report is

```
CPUID is present
CPU Info:
------------------
  vendor_str : `AuthenticAMD'
  vendor id  : 1
  brand_str  : `AMD Ryzen 7 1700 Eight-Core Processor          '
  family     : 15 (0Fh)
  model      : 1 (01h)
  stepping   : 1 (01h)
  ext_family : 23 (17h)
  ext_model  : 1 (01h)
  num_cores  : 8
  num_logical: 16
  tot_logical: 16
  L1 D cache : 32 KB
  L1 I cache : 64 KB
  L2 cache   : 512 KB
  L3 cache   : 16384 KB
  L4 cache   : -1 KB
  L1D assoc. : 8-way
  L2 assoc.  : 8-way
  L3 assoc.  : 16-way
  L4 assoc.  : -1-way
  L1D line sz: 64 bytes
  L2 line sz : 64 bytes
  L3 line sz : 64 bytes
  L4 line sz : -1 bytes
  SSE units  : 128 bits (authoritative)
  code name  : `Ryzen 7 (Summit Ridge)'
  features   : fpu vme de pse tsc msr pae mce cx8 apic mtrr sep pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht pni pclmul monitor ssse3 cx16 sse4_1 sse4_2 syscall movbe popcnt aes xsave osxsave avx mmxext nx fxsr_opt rdtscp lm lahf_lm cmp_legacy svm abm misalignsse sse4a 3dnowprefetch osvw skinit wdt ts ttp tm_amd hwpstate constant_tsc fma3 f16c rdrand aperfmperf avx2 bmi1 bmi2
```

svm is enabled..

**Comment by teddyfold** [comment]
I have the same problem, with vmware pro 11 and parallels the app would either crashes or hang my machine. Docker doesn't  work either.

ended up with vmware pro 10.

**Comment by JoelNichols** [comment]
VirtualBox works just fine for me with these patches. Haven't tried VMWare or Parallels but don't see much point as it seems fairly established to me that they won't work.

Thing is, should this even be an issue on this repository? This isn't an issue with the patches themselves but rather the fact that Mac app developers aren't going to be rushing to add AMD virtualisation support.

**Comment by LiuJiangshan** [comment]
> Except Virtualisation )
> My motherboard ASRock A320M-HDV. I don't know where to look any difference more (
> I can share my config and kexts from Clover

Can you share your config and kexts from Clover?

**Comment by zalivar71** [comment]
> @zalivar71 Can you share your config and kexts from Clover?

@LiuJiangshan Hi,
Sure. Don't forget change S/N in SMbios 
https://yadi.sk/d/XD_d2iUDqHAiyg
