### ISSUE TITLE
Can't boot with the kernel from commit ed8082f

### ISSUE THREAD

**Issue by alexfjw** [AMD-OSX/AMD_Vanilla#37]
I can't boot using the latest kernel (commit ed8082f)
I'm on a 3200g, no issues booting with the previous commit.

Not sure if its because I'm on 17G7024 right now.
I'm also unable to boot into the 17G8030 updater to complete the update using both the previous kernel and current kernel.

**Comment by CarbonCopy4V** [comment]
same here, tried to apply the latest changes and got stuck during boot, using 2700x and Vega 64, Revertet the changes and worked again

**Comment by dermarder** [comment]
I have the same issue using Ryzen 1700 and a RX 570.

**Comment by XLNCs** [comment]
only latest version of macos is supported now
```High Sierra 10.13.6 (17G65, 17G66, 17G8030)
Mojave 10.14.6 (18G84, 18G87)```
other previous versions patches has been removed. 
make sure you are on the above mentioned macos versions

**Comment by dermarder** [comment]
Thank you very much! it works great for me now.
