### ISSUE TITLE
Kexts Files

### ISSUE THREAD

**Issue by umeent** [AMD-OSX/AMD_Vanilla#39]
Place the required Kexts according to your system specs in your USB EFI kexts folder EFI/EFI/CLOVER/kexts/Other/

How Can I do this? how can I found this files?

**Comment by kiennguyen94** [comment]
See https://vanilla.amd-osx.com/setting-up-clover-for-amd-vanilla/kexts.html
Download all the kext you need, extract them to that path `EFI/EFI/CLOVER/kexts/Other/`
On your first boot, only get the bare essential, I.e VirtualSMC.kext NullCPUPowerManagement.kext Whatevergreen.kext and Lilu.kext.
Make sure you can boot first, then proceed to backup and then add more kext.

**Comment by umeent** [comment]
Is there any way I can Install Mac Mojave on USB Bootable without a Macbook
or iMac?

**Comment by zalivar71** [comment]
@umeent Hi. You have to boot from one USB Drive (following instrictions) and select another one USB Drive for installation.

**Comment by umeent** [comment]
I haven't a Mac. How Can I Bootable this without a Mac?

**Comment by kiennguyen94** [comment]
@umeent  Just follow this guide from start https://vanilla.amd-osx.com/getting-the-macos-installer.html 
The guide starts from windows, so you should be good.

**Comment by dhinakg** [comment]
Not related to the patches. We do not provide guide support here. If you are trying to make a bootable installer see [the AMD OS X KB](https://kb.amd-osx.com).
