### ISSUE TITLE
How about performance with these patches comparing to Intel?

### ISSUE THREAD

**Issue by HoshiYamazaki** [AMD-OSX/AMD_Vanilla#4]
As title says - I know that there in macOS we have specific patches in the kernel for Intel so?
Are there any real benchmarks about this?

**Comment by Shaneee92** [comment]
Not sure what you are looking for exactly but, https://img.amd-osx.com/images/2019/03/28/Screenshot-2019-03-27-at-17.37.16.png

**Comment by HoshiYamazaki** [comment]
Seems to be better than my i5-6600, so, I hope there are no specific edge case that make performance worse on AMD.

Will be patches in this repository merged into Clover so we will not be forced to do any configuration?

**Comment by tvhung83** [comment]
Quick question: is it working on 10.14.4? Mine is not able to boot after updating.

**Comment by mikigal** [comment]
@tvhung83 read README.md please

**Comment by tvhung83** [comment]
@mikigal hah, I swear I read before it's updated, thanks anyway 👍

**Comment by mikigal** [comment]
Windows vs macOS

![Bez tytułu](https://user-images.githubusercontent.com/10632503/55239721-90f27b00-5237-11e9-9155-51b10f9de8d6.png)
![3nqlu2m0eo](https://user-images.githubusercontent.com/10632503/55239722-90f27b00-5237-11e9-83b4-5a46001bb1a9.png)
![1ts3op9nvb](https://user-images.githubusercontent.com/10632503/55239762-a4054b00-5237-11e9-9047-63a4f468bcca.png)
