### ISSUE TITLE
Misunderstand the documentation

### ISSUE THREAD

**Issue by nguyennb9** [AMD-OSX/AMD_Vanilla#40]
This is not really a the technical issue. I don't understand this line in the README then I don't know what to do with the file `patched.plist`.
`
NOTE : If your are making your own clover config then use patches.plist to copy the patches manually.
`
Can you help to provide the more detail instruction?

**Comment by dhinakg** [comment]
If you are not using the template `config.plist` copy the patches from `patches.plist` into your existing `config.plist`.
