### ISSUE TITLE
Mouse and Keyboard ISSUE

### ISSUE THREAD

**Issue by umeent** [AMD-OSX/AMD_Vanilla#41]
Hello
I have a problem when I want install MAC after boot and I see Install menu.
Mouse and keyboard after 10 second get freeze and doesn't work.
This is my PC spec:
Cpu AMD Ryzen 2700x
Motherboard Msi x470 gaming pro
VGA Radeon R9 280x
Keyboard B700 bloody
Mouse V4 bloody

**Comment by Shaneee92** [comment]
Not patches related. Closing.
