### ISSUE TITLE
iMessage & FaceTime does not work with native patches.

### ISSUE THREAD

**Issue by IsraelThomas** [AMD-OSX/AMD_Vanilla#43]
I have tried everything on clover to make iMessage and FaceTime to work. My build is a Risen 1700 CPU. Any suggestions?

**Comment by spova** [comment]
What Wifi/BT hardware do you use?

**Comment by IsraelThomas** [comment]
I use an Ethernet port, My hardware does not have any Wifi/BT! The Ethernet is Realtek® 8111H Gigabit LAN controller. I just can't get iMessage & FaceTime to work. Everything else work good. Thank you for your help! :)

**Comment by spova** [comment]
Without appropriate Wifi/BT module it doesn’t work, I’m afraid. I recommend you to buy one of the inexpensive modules from real macs. I personally use BCM94360CS2 card and every feature works well.

**Comment by dhinakg** [comment]
No, you do not need proper WiFi/BT to have iMessage/FaceTime.
Closing as this is not related to the patches.
