### ISSUE TITLE
Kernel Panic: AppleIntelMCE: Controller: This platform does not support CMCI

### ISSUE THREAD

**Issue by wtongze** [AMD-OSX/AMD_Vanilla#46]
Hi there,
I am keep getting this “Kernel Panic: AppleIntelMCE: Controller: This platform does not support CMCI” issue when I try to install MacOS 10.15 Catalina on my AMD build after I updated to the latest version of config.plist and patch.plist. Is there any solutions to this issue?

![BB3A1722-6300-40F3-AAA6-DA27F3927B6F.jpeg](https://i.loli.net/2019/10/09/ur5UMtEv1zG8mg6.jpg)

FYI:
CPU: AMD Ryzen 2600
Motherboard: Gigabyte Aorus M B450

No issue on installing MacOS 10.14.6 Mojave though.

Thanks

**Comment by collinkreutzer** [comment]
Having the same issue. Mojave works just fine.
CPU: AMD Ryzen 5 2600
MB: AsRock B450M Pro4

**Comment by hsombini** [comment]
Quote from XLNC commit, this kext solved the problem for me

> If using SMBIOS ( MacPro6,1 , MacPro7,1 , iMacPro1,1 ) the AppleIntelMCEReporter.kext might panic so to prevent that you need to either use a different SMBIOS model or use a disabler kext from here :
> https://github.com/acidanthera/bugtracker/files/3703498/AppleMCEReporterDisabler.kext.zip

**Comment by wtongze** [comment]
> Quote from XLNC commit, this kext solved the problem for me
> 
> > If using SMBIOS ( MacPro6,1 , MacPro7,1 , iMacPro1,1 ) the AppleIntelMCEReporter.kext might panic so to prevent that you need to either use a different SMBIOS model or use a disabler kext from here :
> > https://github.com/acidanthera/bugtracker/files/3703498/AppleMCEReporterDisabler.kext.zip

It now works like a charm :)
Thx
