### ISSUE TITLE
Kernel Panic - [CPU 31 has no HPET assigned to it]

### ISSUE THREAD

**Issue by rightedges** [AMD-OSX/AMD_Vanilla#5]
I'm using a threadripper 1950x and got below kernel panic during installation:

Wed Mar 27 18:22:07 2019

*** Panic Report ***
panic(cpu 18 caller 0xffffff7f94437b83): CPU 31 has no HPET assigned to it
Backtrace (CPU 18), Frame : Return Address
0xffffff8736b03cb0 : 0xffffff8010baeb0d 
0xffffff8736b03d00 : 0xffffff8010ce8653 
0xffffff8736b03d40 : 0xffffff8010cda07a 
0xffffff8736b03db0 : 0xffffff8010b5bca0 
0xffffff8736b03dd0 : 0xffffff8010bae527 
0xffffff8736b03ef0 : 0xffffff8010bae373 
0xffffff8736b03f60 : 0xffffff7f94437b83 
0xffffff8736b03fa0 : 0xffffff8010b5b0ce 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleIntelCPUPowerManagement(220.0)[154EEBE6-51B3-3F95-9EF9-F00A3C28D344]@0xffffff7f94431000->0xffffff7f9445afff

BSD process name corresponding to current thread: kernel_task
Boot args: dart=0 nv_disable=1 -v root-dmg=file:///Install%20macOS%20Mojave.app/Contents/SharedSupport/BaseSystem.dmg

Mac OS version:
18D109

Let me know if you need anything to troubleshoot the problem. Thanks.

**Comment by rightedges** [comment]
Another sample

Wed Mar 27 21:58:20 2019

*** Panic Report ***
panic(cpu 2 caller 0xffffff7f90637b83): CPU 31 has no HPET assigned to it
Backtrace (CPU 2), Frame : Return Address
0xffffff8732af3cb0 : 0xffffff800cdaeb0d 
0xffffff8732af3d00 : 0xffffff800cee8653 
0xffffff8732af3d40 : 0xffffff800ceda07a 
0xffffff8732af3db0 : 0xffffff800cd5bca0 
0xffffff8732af3dd0 : 0xffffff800cdae527 
0xffffff8732af3ef0 : 0xffffff800cdae373 
0xffffff8732af3f60 : 0xffffff7f90637b83 
0xffffff8732af3fa0 : 0xffffff800cd5b0ce 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleIntelCPUPowerManagement(220.0)[154EEBE6-51B3-3F95-9EF9-F00A3C28D344]@0xffffff7f90631000->0xffffff7f9065afff

BSD process name corresponding to current thread: kernel_task
Boot args: dart=0 nv_disable=1 root-dmg=file:///Install%20macOS%20Mojave.app/Contents/SharedSupport/BaseSystem.dmg

Mac OS version:
18D109

Kernel version:
Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
Kernel UUID: 1970B070-E53F-3178-83F3-1B95FA340695
Kernel slide:     0x000000000ca00000
Kernel text base: 0xffffff800cc00000
__HIB  text base: 0xffffff800cb00000
System model name: iMac14,2 (Mac-27ADBB7B4CEE8E61)

**Comment by rightedges** [comment]
Looks like I was missing NullCPUPowerManagement. All working now.

**Comment by nguyennb9** [comment]
> Looks like I was missing NullCPUPowerManagement. All working now.

I got the same issue, even when I have the `NullCPUPowerManagement` kext I still get into that error. How did you go through it?

**Comment by vdavdev** [comment]
Hi, this might be a stupid answer, but go check your NullCPUPowerManagement.kext, mine is a zero size file(Can't find it's github repo, I downloaded one from the forum), after I replaced it with a valid one (With binary, info.plist, etc), it booted successfully now, good luck:)

**Comment by vdavdev** [comment]
> > Looks like I was missing NullCPUPowerManagement. All working now.
> 
> I got the same issue, even when I have the `NullCPUPowerManagement` kext I still get into that error. How did you go through it?

Hi, this might be a stupid answer, but go check your NullCPUPowerManagement.kext, mine is a zero size file(Can't find it's github repo, I downloaded one from the forum), after I replaced it with a valid one (With binary, info.plist, etc), it booted successfully now, good luck:)
