### ISSUE TITLE
Catalina Previous shutdown error:5 Unable to update or install. iMac pro 2017 conf. 

### ISSUE THREAD

**Issue by sgonzalezdev** [AMD-OSX/AMD_Vanilla#50]
I cannot update or clean install using this in Catalina. My conf is Ryzen 5 2600x, Radeon 560 4gb and Asus Rog 470-F. Whenever I try to update or clean install, clover stops with previous shutdown 5. Any idea?

**Comment by dhinakg** [comment]
Not related to the patches.

**Comment by sgonzalezdev** [comment]
But I cannot install smooth Mohave but not Catalina. Mohave makes a smooth installation with this parch. It is just Catalina.
