### ISSUE TITLE
Support 19A602 Catalina 10.15.0 Supplemental Update?

### ISSUE THREAD

**Issue by tedli** [AMD-OSX/AMD_Vanilla#54]
Hi.

The 19A602 had been released for several days. Can we update to this version use the latest patch?

I'm running with 19A583 now, everything works fine. Thanks.

**Comment by TheJKM** [comment]
Just updated successfully wird existent patches for Catalina.

**Comment by jessesix** [comment]
Updated successfully

**Comment by tedli** [comment]
![image](https://user-images.githubusercontent.com/3324663/67174036-313a0800-f3f3-11e9-854e-145052eb5da2.png)
Happy with `19A602`.

💯
