### ISSUE TITLE
An internet connection was required to install mac os catalina

### ISSUE THREAD

**Issue by jonathantanuwijaya** [AMD-OSX/AMD_Vanilla#56]
i have this issue when boot to install catalina using usb drive , i don't what's cause this but i've added RealtekRTL8111.kext
my config :
CPU Ryzen 5 2400g
MB Msi B350M Bazoka
GPU Radeon RX560 
Anyone have some ideas to fix this ?

**Comment by parorisim** [comment]
just try again and again...
or disconnect and reconnect your network...

**Comment by jonathantanuwijaya** [comment]
i've do that but nothing changed

**Comment by jonathantanuwijaya** [comment]
i'm using lan

**Comment by parorisim** [comment]
i use the same motherboard and kext as you. just tried many times and finally worked...

**Comment by jonathantanuwijaya** [comment]
I've do that more than 10 times but nothing changed

**Comment by SinCOS** [comment]
check the datatime

**Comment by jonathantanuwijaya** [comment]
I always can't connect to the internet while i'm try to install mac os , but that doesn't happen while i'm open windows , any solutions guys ?

**Comment by hberthier123** [comment]
Use clover 5058 instead, it fixed for me and everyone who've tried

**Comment by dhinakg** [comment]
Not related to the patches.
