### ISSUE TITLE
Error Random Seed with 10.14.2, 10.14.3 and 10.13.6 Build 17G2208 installer

### ISSUE THREAD

**Issue by andreszerocross** [AMD-OSX/AMD_Vanilla#6]
Try making installer mojave version 10.14.2, 10.14.3 and high Sierra 10.13.6 Build 17G2208 and got stuck in ERROR RANDOM SEED +++++++++++++

But with version 10.14.4 Build 18EE226 Mojave and High Sierra 10.13.6 Build 17G65,, patch working well. No stuck in this stage.

I just want to inform it. I create installer with Create install media method

**Comment by dhinakg** [comment]
The patches are version specific. They will break with an update.
