### ISSUE TITLE
Dual Monitor not working.  Black flash and high Voltage. Catalina. 

### ISSUE THREAD

**Issue by sgonzalezdev** [AMD-OSX/AMD_Vanilla#61]
I have RX 560, after the upgrade, the DIV port does not work. Dual monitor is not working. If I connect another monitor, it starts flashing and cause high voltage.  HDMI is the only port working.

**Comment by IOIIIO** [comment]
Doesn't sound like a kernel problem. Consider using WhateverGreen.kext and trying graphics related fixes instead.
