### ISSUE TITLE
hackintosh panic after boot into install Page

### ISSUE THREAD

**Issue by xVanTuring** [AMD-OSX/AMD_Vanilla#69]
**CPU:** AMD Ryzen 5 1600
**macOS version:** 10.13.6 (17G66)
**15h/16h or 17h:** 17h
**I am using and can reproduce on the latest patches:** yes

**Describe the bug**
After boot into the macOS install page , it'll freeze in 10 second, I guess it's panicked. 
> During the boot, there are `unsupported CPU`  `unsupported PCH` lines. 

Kexts using: 
* Lilu
* VirtualSMC
* RealtekRTL8111
* WhateverGreen
* NullCPUPowerManagement

**Comment by xVanTuring** [comment]
PS: I had made a successful hackintosh month ago on this computer.

**Comment by IOIIIO** [comment]
> During the boot, there are unsupported CPU unsupported PCH lines.

Nothing to be worried about, standard behaviour.

Make sure you have a working version of NullCPUPowerManagement, and if you manage to do it in those 10 seconds, open the log from Utilities, and post the information you get from there.

**Comment by xVanTuring** [comment]
**OMG**, after replacing the `NullCPUPowerManagement` by the one from [`onedrive`](https://onedrive.live.com/?authkey=%21APjCyRpzoAKp4xs&id=FE4038DA929BFB23%21455158&cid=FE4038DA929BFB23), it worked!
Something is wrong with the one [`vanilla` hosted](https://vanilla.amd-osx.com/assets/files/NullCPUPowerManagement-1.0.0d2-2019-10-22%2016.19.27.zip), I guess
