### ISSUE TITLE
AMD 3700x + 5700xt   I cannot update to 10.15.1 Black Screen During Installation

### ISSUE THREAD

**Issue by tingmin123** [AMD-OSX/AMD_Vanilla#70]
I cannot update to 10.15.1. I can start the update in my Catalina install. It download, starts the update, but after reboot if I choose to boot from the Installer (on the data drive), my boot hangs at '+++++++'.
I have no clue how to move along.
Does anyone else have this problem? Is this Clover related?

**Comment by SandnerSoft** [comment]
I'have this issue after update to 10.15.1:

[https://github.com/AMD-OSX/AMD_Vanilla/issues/64](url)

**Comment by dhinakg** [comment]
User error. The mainstream patches do not support 10.15.1 yet. 10.15.1 patches are in testing.
