### ISSUE TITLE
cpu temp is 0

### ISSUE THREAD

**Issue by arnolix** [AMD-OSX/AMD_Vanilla#71]
**CPU: Ryzen 3700X
**macOS version: 10.15.0
**15h/16h or 17h: 17h
**I am using and can reproduce on the latest patches:**

**Describe the bug**
CPU temperature is 0 and CPU fan speed cannot be displayed...; app: istat menu 6.4.0

**Screenshots**

**Comment by lorethefixer** [comment]
Same with threadripper 1920x on 10.13.6
Patch:17h

**Comment by Shaneee92** [comment]
This is not a kernel issue. You'll need the correct LPC kext for your motherboard,

- LPC chip sensors, motherboard parameters like FAM, Voltages, temperatures
- ITEIT87x for chips ITE 87xx, 86xx, usually present on Gigabyte motherboards
- W836x for chips Winbond/Nuvoton 83xxx, NCT67xx, usually present on ASUS motherboards
- F718x for chips Fintek
- PC8739x for chip SMC

Kext downloads here, https://github.com/CloverHackyColor/FakeSMC3_with_plugins/releases/download/241/Release.241.zip

Be sure to use the FakeSMC included here. If using VirtualSMC remove and use FakeSMC.
