### ISSUE TITLE
Please add support for 10.15.1

### ISSUE THREAD

**Issue by Uncle-Nine** [AMD-OSX/AMD_Vanilla#72]
┭┮﹏┭┮

**Comment by Justatee** [comment]
@Uncle-Nine Try OpenCore bro, Im running macOS Catalina 10.15.1 with RX 5700 XT GPU.  
Try [OpenCore vanilla guide](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/) this, i think it should help you run your system with 10.15.1 version of macOS
