### ISSUE TITLE
ocb: loadimage failed - unsupported

### ISSUE THREAD

**Issue by parorisim** [AMD-OSX/AMD_Vanilla#74]
**CPU:**
3600
**macOS version:**
10.15.1
**15h/16h or 17h:**
17h
**I am using and can reproduce on the latest patches:**
yes
**Describe the bug**
If I boot macOS recovery from opencore, the error "ocb: loadimage failed - unsupported" occurred.
I searched for a long time but can't resolve it.

related:
https://github.com/acidanthera/bugtracker/issues/510
https://github.com/acidanthera/bugtracker/issues/360

**Comment by rektimus** [comment]
Are you using HFSPlus.efi or VBox?

**Comment by parorisim** [comment]
Tried both and no luck :(

**Comment by Zachwang007** [comment]
mine is same as yours, i cannot load the recovery

**Comment by yscoolangel** [comment]
mine is same as yours,tried both and cannot load the recovery,

**Comment by IOIIIO** [comment]
Sounds like either a configuration or OC issue.
