### ISSUE TITLE
Patch update request for 10.15.1 (I have macOS 10.15 (19A602))

### ISSUE THREAD

**Issue by SevenXP** [AMD-OSX/AMD_Vanilla#75]
Hi, i have GL702ZC ( Ryzen 7 1700 + RX 580 4GB + 16 GB) When I'm starting update with MacOS 10.15 to 10.15.1, when clover finish loading (console write log on screen white string lines) before the Apple screen appears (for update) 
Console screen changed to black screen and screen freezes and nothing happens

Sorry for my English

**Comment by sgonzalezdev** [comment]
You have to add last version of whatevergreen and Lilus that prevent it happening. I was able to update successfully.

**Comment by dhinakg** [comment]
Not related to the patches.

**Comment by SevenXP** [comment]
> 
> You have to add last version of whatevergreen and Lilus that prevent it happening. I was able to update successfully.
I have clover 2.5k ver 5096 What version of clover do you have?

> Not related to the patches.
What can this relate to, that I would correctly create questions in the future?

**Comment by sgonzalezdev** [comment]
I think I have 5094 or so
