### ISSUE TITLE
3, 7, 29 ,31 kernel patch not found

### ISSUE THREAD

**Issue by Pramy** [AMD-OSX/AMD_Vanilla#78]
**CPU:**  2600x
**macOS version:**   Catalina 10.15.1
**15h/16h or 17h:**   17h
**I am using and can reproduce on the latest patches:**
Yes
**Describe the bug**
I use opencore 0.5.2
when os start up, some patches cant not be found
- algrey - cpuid_set_cache_info - cpuid 0x8000001D instead 0
- algrey - - skip cpuid_cores_per_package test
- algrey - lapic_init - remove version check and panic
- algrey - lapic_interrupt - skip checks and prevent panic 

**Screenshots**
![1](https://user-images.githubusercontent.com/13444999/70460775-12eab180-1af2-11ea-8906-d0717316b98e.jpg)

**Comment by Pramy** [comment]
I use branch:experimental-opencore `patch.plist`( chang `19.99. 99`  to `18.99.99`  at MaxKernel node), It works fine

**Comment by arximus88** [comment]
In case if somebody will looking for the same. For old dated config.plist need to replace whole Patch branch, in Root/Kernel with fresh downloaded from patch.plist

**Comment by kloppervok** [comment]
I'm getting the same error still.

CPU: 3600
macOS version: Catalina 10.14.6
15h/16h or 17h: 17h
I am using and can reproduce on the latest patches:
Yes
Describe the bug
Roughly same as above, but it fails at result 3, algrey - cpuid_set_cache_info - cpuid 0x8000001D instead 0
Halting in critical error. 

I've grafted the patch properly.
