### ISSUE TITLE
Threadripper 3970x 

### ISSUE THREAD

**Issue by fabiosun** [AMD-OSX/AMD_Vanilla#79]
Hi
17H patches are compatible with new threadripper's family?
I would like to use it in High Sierra (17G8037)

Thank you in advance for any tips

**Comment by XLNCs** [comment]
support added !

**Comment by fabiosun** [comment]
Grazie..but where? :)

**Comment by jasin755** [comment]
Hi. Is 3rd Threadripper supported? If not, does exist any estimation? Thanks.
