### ISSUE TITLE
TP-Link TL-WN823N wireless card not working in macOS Mojave

### ISSUE THREAD

**Issue by thatdhruv** [AMD-OSX/AMD_Vanilla#8]
Hi! I just installed macOS Mojave on my AMD machine using the native Zen patch. But unfortunately, I can't get the wifi working.
To be precise, I installed the drivers from TP-Link's official website, and for some reason, I am unable to use the wireless card. I wonder if the drivers or maybe the application might be 32-bit. (OPEMU is not currently supported by the vanilla patch, then I'll have to wait till it does)

Hoping for any help. Thanks in advance

**Comment by XLNCs** [comment]
@thatdhruv 
Hi !
Seems like its a USB port issue and not the kernel issue .

**Comment by thatdhruv** [comment]
Thank you for your reply and advice @XLNCs
Assuming my problem to be a USB port issue, then why doesn't the WiFi utility launch on startup (it used to show up in the menu bar)
I've plugged and unplugged several other USB devices, checking if my problem persisted to be a USB port problem, but the ports work just fine.
For reference, I downloaded the driver for macOS 10.14 beta from https://www.tp-link.com/us/support/download/tl-wn823n/#Driver

Again, thank you very much for helping.

**Comment by XLNCs** [comment]
@thatdhruv 
Ok ! i looked at the driver pkg and the provided status bar app is 32 bit 
and without it you cannot connect to any wifi.

Solution : 
- Reinstall your wifi driver
- Download the attached statusbar app and place it in /Library/Application Support/WLAN/
- Open terminal and type 
`sudo chmod -R 777 /Library/Application Support/WLAN/StatusBarApp.app`
`sudo chown -R 0:0 /Library/Application Support/WLAN/StatusBarApp.app`
- Reboot
[StatusBarApp.zip](https://github.com/AMD-OSX/AMD_Vanilla/files/3193997/StatusBarApp.zip)

**Comment by thatdhruv** [comment]
THANKS @XLNCs for the help!
I'm now closing this issue
👍😎
