### ISSUE TITLE
Please add support for OSX 10.15.2

### ISSUE THREAD

**Issue by MScuti** [AMD-OSX/AMD_Vanilla#80]
If you have a support question, please go to the discord or the forum.

**Comment by XLNCs** [comment]
support added !

**Comment by dhinakg** [comment]
![image](https://user-images.githubusercontent.com/17605561/70636070-f25e4c80-1c02-11ea-9dee-388c933b3e3f.png)
Use the patch update template next time.

**Comment by surajmandalcell** [comment]
Duplicate of #81
