### ISSUE TITLE
Patch update request for 10.15.2 (build 19C57)

### ISSUE THREAD

**Issue by senthilklpmicro** [AMD-OSX/AMD_Vanilla#81]
Patch update request for 10.15.2 (build 19C57)

I have used the current version of Patch till 10.15.1. Worked fine. After downloading the 10.15.2 update on mac 10.15.1, the installation will not boot.

Thanks in advance !

**Comment by nomco** [comment]
I need too

**Comment by zalivar71** [comment]
I think a lot of guys need this patch

**Comment by moos** [comment]
Any ETA on a patch for 10.15.2?  Spent a good portion of Sunday with OpenCore and still don't have a healthy boot.

**Comment by dhinakg** [comment]
There are no ETAs at this time.

**Comment by moos** [comment]
Thanks -- I'm going to try 10.15.1.

**Comment by screenpunch** [comment]
Did you get 10.15.1 working? I'm struggling to find a source to download that specific version of Catalina

**Comment by zalivar71** [comment]
Yes, this version working stable for me. Maybe you should use torrents to find specific version. 
<img width="698" alt="изображение" src="https://user-images.githubusercontent.com/54080051/72250109-e7d11180-360b-11ea-8bfe-67d17d59a8f0.png">

**Comment by moos** [comment]
@screenpunch I did find a version of 10.15.1 to download - however I couldn't create the USB installer.  I don't remember the details -- but I did try very hard.  Finally gave up on that, went back OpenCore & 10.15.2 using an EFI from one of the chat rooms and after some hick-ups, it's now running on my AMD machine.

**Comment by alanlicz** [comment]
> @screenpunch I did find a version of 10.15.1 to download - however I couldn't create the USB installer. I don't remember the details -- but I did try very hard. Finally gave up on that, went back OpenCore & 10.15.2 using an EFI from one of the chat rooms and after some hick-ups, it's now running on my AMD machine.
I have the bat file to create the usb installer? But can you share with me how to download 10.15.1?

**Comment by screenpunch** [comment]
@alanlicz & @moos  https://github.com/corpnewt/gibMacOS has 10.15.1 BETA. I also found it difficult to to find a copy of 10.15.1.

**Comment by alanlicz** [comment]
@screenpunch yeah but the 10.15.1 beta is also not supported by clover currently

**Comment by zalivar71** [comment]
I have torrent (and magnet link) with 10.15.1 from Apple Store - but I'm not sure that share it here good idea )

**Comment by Pavo-IM** [comment]
Just switch to OpenCore, it currently supports up 10.15.3 beta 2.

**Comment by nomco** [comment]
love clover no OC



---Original---

**Comment by TritiatedWater** [comment]
@Pavo-IM do mind sharing your config?

**Comment by EnekoT2001** [comment]
> I have torrent (and magnet link) with 10.15.1 from Apple Store - but I'm not sure that share it here good idea )

Tbh send me an email or an DM on twitter (i have them on my profile) with the link if you can

**Comment by distupid** [comment]
opencore is the trendence.   my devices are asus prime x470 ,2700x  ,work well on 10.15.3(from OTA update)

**Comment by tedli** [comment]
> Just switch to OpenCore, it currently supports up 10.15.3 beta 2.

Hi @Pavo-IM ,
Is the 'switch' here you mean that you had a working AMD hackintosh booted by Clover, and you replace existing Clover with OpenCore? Or you had a fresh install with OpenCore?

Please have a look at https://github.com/AMD-OSX/AMD_Vanilla/issues/92

**Comment by Shaneee** [comment]
Patches supported on OpenCore. Clover support dropped for now.
