### ISSUE TITLE
XCode tool fails to run on ryzentosh (i386 arch), yet runs on legit catalina laptop

### ISSUE THREAD

**Issue by fer662** [AMD-OSX/AMD_Vanilla#84]
It is my understanding that i386 binaries shouldn't run on Catalina, however, there's an XCode command line tool used for compiling asset catalogs that runs fine on my catalina macbook pro. How is that even possible? I verified and both machines have the same binary that only has i386 in it

`Desktop:iOS fernandomazzon$ file /Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/Library/Xcode/Overlays/IBCocoaTouchImageCatalogTool 
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/Library/Xcode/Overlays/IBCocoaTouchImageCatalogTool: Mach-O executable i386
Desktop:iOS fernandomazzon$ /Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/Library/Xcode/Overlays/IBCocoaTouchImageCatalogTool 
Illegal instruction: 4
`

**Comment by IOIIIO** [comment]
Catalina has a bit of remaining x86 support, as you've noticed with your laptop. Our kernel patches however don't support x86 which is where the issue arrises.
