### ISSUE TITLE
processor can't virtualize 

### ISSUE THREAD

**Issue by jonathantanuwijaya** [AMD-OSX/AMD_Vanilla#89]
**CPU:*Ryzen 5 2400G*
**macOS version:*10.14.6*
**17h:**
**I am need the virtualization to run some tools like android emulator ,xampp and docker :**

**Describe the bug**
processor doesnot support virtualization
![Screenshot at Feb 06 15-16-51](https://user-images.githubusercontent.com/50512896/73918226-c6560380-48f3-11ea-9702-a129bdde0cc3.png)

**Screenshots**

**Comment by tedli** [comment]
Hi @jonathantanuwijaya ,
FYI.
https://github.com/moby/hyperkit/issues/230
