### ISSUE TITLE
Kaveri Family 

### ISSUE THREAD

**Issue by MrBenFTW** [AMD-OSX/AMD_Vanilla#9]
Hi, my CPU is a AMD x4 860K.

I am running macOS High Sierra and I want to install Mojave instead. 

Should I use 15h,16h or 17h? 

Thank you!

**Comment by Shaneee92** [comment]
Use the 15h 16h patches. That CPU falls under the 15h family.

**Comment by MrBenFTW** [comment]
Thanks for the reply, I installed it however after the reboots, during the setup screen I get as far as the privacy prompt and when I press continue, it reboots my PC.

**Comment by SleepingPanda** [comment]
I don't even get that far. Mind telling me what guide you used if any or your config.plist settings?

**Comment by MrBenFTW** [comment]
vanilla.amd-osx.com

I used the 15/16h

**Comment by SleepingPanda** [comment]
Thanks. That's the same guide I used but I'm stuck at booting the USB installer where I get some graphical corruption. I won't hijack your thread any longer. Take care and I hope they solve your issues.

**Comment by MrBenFTW** [comment]
> Thanks. That's the same guide I used but I'm stuck at booting the USB installer where I get some graphical corruption. I won't hijack your thread any longer. Take care and I hope they solve your issues.
> 
> Edit: Lmao I fixed it by switching from a USB 3.0 front panel port to a rear USB 2.0 port. I hope this gets put into that vanilla guide in case anyone gets stuck there. Cheers.

I am also using a 750ti. 

I had some issues as well but I eventually managed to fix them, I’ll send you my Kext and configure file later :)

**Comment by tvhung83** [comment]
> Edit: Lmao I fixed it by switching from a USB 3.0 front panel port to a rear USB 2.0 port. I hope this gets put into that vanilla guide in case anyone gets stuck there. Cheers.
I believe this has nothing to do with this patch, you probably run into it for every specs, it's a common issue (USB port limit).
