### ISSUE TITLE
Can I replace existing Clover with OpenCore

### ISSUE THREAD

**Issue by tedli** [AMD-OSX/AMD_Vanilla#92]
I use my AMD hackintosh for quite a long time. As someone said that 'I'm not your boss, neither paid you ever', but I can use these awesome patches for free, I'm very appreciated.

I'm using Clover, and not willing to do a fresh reinstall of OS. I read OpenCore manual, create an EFI folder following [this guide](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/amd-config.plist/amd-config), replaced Clover's EFI folder with the OpenCore one, the system didn't boot.

![image](https://user-images.githubusercontent.com/3324663/74080225-b3226f80-4a7c-11ea-8b18-a9439e60cb87.png)

Seemed VirtualSMC troubles with authentication things.

Is it possible to replace an existing Clover booted system with OpenCore, or just I didn't read the manual well with missing configs caused this?

**Comment by IOIIIO** [comment]
Issues on Github are for bugs with the actual patches, not for issues installing.
Try adding eitiher npci=0x2000 or 0x3000 in your bootflags and if it doesn't work try contacting us on the Discord instead.
