### ISSUE TITLE
3, Patches not found 

### ISSUE THREAD

**Issue by kloppervok** [AMD-OSX/AMD_Vanilla#93]
**CPU:**
Ryzen 5 3600
**macOS version:**
10.14.6
**15h/16h or 17h:**
17h
**I am using and can reproduce on the latest patches:**
Yes
**Describe the bug**
Describe the bug
I use opencore 0.5.5
when macos boots some patches cant not be found
Kernel patcher result 3 for kernel (algrey - cpuid_set_cache_info - cpuid 0x8000001D instead 0) - not found 

As per issue 78, I tried changing the MaxKernel values from 19.99.99 to 18.99.99, with no resulting changes whatsoever.

**Comment by IOIIIO** [comment]
Those are unnecessary patches which don't apply to your macOS version. They can be safely ignored or removed from your config.
